# [컴페티션] 머신러닝 성능 극대화
- 대회 주제 : Binary Classification with a Bank Churn Dataset
- 대회 링크 : https://www.kaggle.com/competitions/playground-series-s4e1
- 평가 항목 : ROC Curve
- 제출일 : 2024년 12월 10일 화요일 7교시
- 평가 항목 점수 : **Private: 0.90599 , Public: 0.90238**
- 수강생 성함 : 송현서

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
!pip install -U autogluon > /dev/null

from autogluon.tabular import TabularDataset, TabularPredictor
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from catboost import CatBoostClassifier, Pool
from catboost.utils import eval_metric

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

������ ��θ� ã�� �� �����ϴ�.
c:\Users\campus3S031\Desktop\iMBank\iM_DiGital_Banker_academy\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df_train = pd.read_csv('/kaggle/input/playground-series-s4e1/train.csv')
df_train.head()

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/playground-series-s4e1/train.csv'

In [5]:
df_test = pd.read_csv('/kaggle/input/playground-series-s4e1/test.csv')
df_test_ov = df_test.copy()
df_test.head()

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,165034,15773898,Lucchese,586,France,Female,23.0,2,0.00,2,0.0,1.0,160976.75
1,165035,15782418,Nott,683,France,Female,46.0,2,0.00,1,1.0,0.0,72549.27
2,165036,15807120,K?,656,France,Female,34.0,7,0.00,2,1.0,0.0,138882.09
3,165037,15808905,O'Donnell,681,France,Male,36.0,8,0.00,1,1.0,0.0,113931.57
4,165038,15607314,Higgins,752,Germany,Male,38.0,10,121263.62,1,1.0,0.0,139431.00

In [6]:
df_orig=pd.read_csv("/kaggle/input/bank-customer-churn-prediction/Churn_Modelling.csv")
df_orig=df_orig.rename(columns={'RowNumber':'id'})
df_orig.head()

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

# Preprocessing

In [7]:
# 진짜 의미가 있는 숫자형 데이터만 MinMaxScaler를 사용함.
# MinMaxScaler와 같은 작동방식으로 사용한다.

scale_cols = ['Age','CreditScore', 'Balance','EstimatedSalary']

for c in scale_cols:
    min_value = df_train[c].min()
    max_value = df_train[c].max()
    df_train[c+"_scaled"] = (df_train[c] - min_value) / (max_value - min_value)
    df_test[c+"_scaled"] = (df_test[c] - min_value) / (max_value - min_value)

In [8]:
df_train.head(2)

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Age_scaled,CreditScore_scaled,Balance_scaled,EstimatedSalary_scaled
0,0,15674932,Okwudilichukwu,668,France,Male,33.0,3,0.0,2,1.0,0.0,181449.97,0,0.202703,0.636,0.0,0.907279
1,1,15749177,Okwudiliolisa,627,France,Male,33.0,1,0.0,2,1.0,1.0,49503.50,0,0.202703,0.554,0.0,0.247483

In [9]:
# train과 test를 합친 다음 인덱스 제거
# 이후 주요 통계 지표 확인

df_all = pd.concat([df_train,df_test]).reset_index(drop=True)
aggs = {
    'Age': ['min','max', 'mean'],       
    'Balance': ['min','max', 'mean','sum'],
    'NumOfProducts': ['mean','sum'],
    'IsActiveMember': ['min','max', 'mean','sum'],
    'CreditScore': ['min','max', 'mean'],
    'EstimatedSalary': ['min','max', 'mean','sum'],
    'id': 'count',
}
df_grps=df_all.groupby(['CustomerId', 'Surname', 'Geography', 'Gender']).agg(aggs).reset_index()
df_grps.columns = list(map(''.join, df_grps.columns.values))
print(len(df_grps))
df_grps.head()

235258

,CustomerId,Surname,Geography,Gender,Agemin,Agemax,Agemean,Balancemin,Balancemax,Balancemean,...,IsActiveMembermean,IsActiveMembersum,CreditScoremin,CreditScoremax,CreditScoremean,EstimatedSalarymin,EstimatedSalarymax,EstimatedSalarymean,EstimatedSalarysum,idcount
0,15565701,Bruno,Spain,Male,49.0,49.0,49.0,0.00,0.00,0.00,...,1.0,1.0,846,846,846.0,90280.70,90280.70,90280.70,90280.70,1
1,15565701,Chineze,France,Male,32.0,32.0,32.0,107209.58,107209.58,107209.58,...,1.0,1.0,705,705,705.0,129822.79,129822.79,129822.79,129822.79,1
2,15565701,Ferri,France,Female,39.0,39.0,39.0,161993.89,161993.89,161993.89,...,0.0,0.0,698,698,698.0,90212.38,90212.38,90212.38,90212.38,1
3,15565701,Ferri,Spain,Male,34.0,34.0,34.0,161993.89,161993.89,161993.89,...,0.0,0.0,707,707,707.0,94912.78,94912.78,94912.78,94912.78,1
4,15565706,Akobundu,France,Male,37.0,40.0,38.5,0.00,0.00,0.00,...,0.5,1.0,612,682,647.0,83256.26,83256.26,83256.26,166512.52,2

In [10]:
aggs = {   
    'Balance': ['min','max', 'mean','sum'],
    'NumOfProducts': ['mean','sum'],
    'IsActiveMember': ['min','max', 'mean','sum'],
    'CreditScore': ['min','max', 'mean'],
    'EstimatedSalary': ['min','max', 'mean','sum'],
    'id': 'count',
}
df_grps1=df_all.groupby(['CustomerId', 'Surname', 'Age', 'Gender']).agg(aggs).reset_index()
df_grps1.columns = list(map('grps1'.join, df_grps1.columns.values))
print(len(df_grps1))
df_grps1=df_grps1.rename(columns={'CustomerIdgrps1':'CustomerId','Surnamegrps1':'Surname',
                                 'Agegrps1':'Age','Gendergrps1':'Gender'})
df_grps1.head()

252537

,CustomerId,Surname,Age,Gender,Balancegrps1min,Balancegrps1max,Balancegrps1mean,Balancegrps1sum,NumOfProductsgrps1mean,NumOfProductsgrps1sum,...,IsActiveMembergrps1mean,IsActiveMembergrps1sum,CreditScoregrps1min,CreditScoregrps1max,CreditScoregrps1mean,EstimatedSalarygrps1min,EstimatedSalarygrps1max,EstimatedSalarygrps1mean,EstimatedSalarygrps1sum,idgrps1count
0,15565701,Bruno,49.0,Male,0.00,0.00,0.00,0.00,2.0,2,...,1.0,1.0,846,846,846.0,90280.70,90280.70,90280.70,90280.70,1
1,15565701,Chineze,32.0,Male,107209.58,107209.58,107209.58,107209.58,1.0,1,...,1.0,1.0,705,705,705.0,129822.79,129822.79,129822.79,129822.79,1
2,15565701,Ferri,34.0,Male,161993.89,161993.89,161993.89,161993.89,1.0,1,...,0.0,0.0,707,707,707.0,94912.78,94912.78,94912.78,94912.78,1
3,15565701,Ferri,39.0,Female,161993.89,161993.89,161993.89,161993.89,1.0,1,...,0.0,0.0,698,698,698.0,90212.38,90212.38,90212.38,90212.38,1
4,15565706,Akobundu,35.0,Male,0.00,0.00,0.00,0.00,1.5,3,...,0.5,1.0,663,787,725.0,83256.26,83256.26,83256.26,166512.52,2

In [11]:
exitGrpBy=['CustomerId', 'Surname',  'Gender','Geography','EstimatedSalary']

exitSrtBy=['CustomerId', 'Surname',  'Gender','Geography',
       'Age', 'Tenure']
##
df_all_Exits=df_all.copy()
df_all_Exits['Exited']=df_all_Exits['Exited'].fillna(-1)
df_all_Exits=df_all_Exits.sort_values(exitSrtBy)
df_all_Exits['Exit_lag1']=df_all_Exits.groupby(exitGrpBy)['Exited'].shift(1)
df_all_Exits['Exit_lag2']=df_all_Exits.groupby(exitGrpBy)['Exited'].shift(2)
df_all_Exits['Exit_lag3']=df_all_Exits.groupby(exitGrpBy)['Exited'].shift(3)

df_all_Exits['Exit_lead1']=df_all_Exits.groupby(exitGrpBy)['Exited'].shift(-1)
df_all_Exits['Exit_lead2']=df_all_Exits.groupby(exitGrpBy)['Exited'].shift(-2)
df_all_Exits['Exit_lead3']=df_all_Exits.groupby(exitGrpBy)['Exited'].shift(-3)

df_all_Exits['Balance_lag_diff1']=df_all_Exits['Balance'].shift(1)
df_all_Exits['Balance_lead_diff1']=df_all_Exits['Balance'].shift(-1)

df_all_Exits=df_all_Exits[['id','Exit_lag1','Exit_lag2','Exit_lag3',
                         'Exit_lead1','Exit_lead2','Exit_lead3',
                          'Balance_lag_diff1','Balance_lead_diff1']]
df_all_Exits=df_all_Exits.fillna(-1).astype('int')
df_all_Exits

,id,Exit_lag1,Exit_lag2,Exit_lag3,Exit_lead1,Exit_lead2,Exit_lead3,Balance_lag_diff1,Balance_lead_diff1
87277,87277,-1,-1,-1,-1,-1,-1,-1,107209
140882,140882,-1,-1,-1,-1,-1,-1,0,161993
160702,160702,-1,-1,-1,-1,-1,-1,107209,161993
259273,259273,-1,-1,-1,-1,-1,-1,161993,0
106193,106193,-1,-1,-1,-1,-1,-1,161993,0
...,...,...,...,...,...,...,...,...,...
189759,189759,-1,-1,-1,-1,-1,-1,0,0
124621,124621,-1,-1,-1,-1,-1,-1,0,135277
97684,97684,-1,-1,-1,-1,-1,-1,0,144591
46972,46972,-1,-1,-1,-1,-1,-1,135277,0
235423,235423,-1,-1,-1,-1,-1,-1,144591,-1

In [12]:
def getGrpsIndv(df_orig,df_train,df_test,grpCols,nm):
    grpBy=[]
    for c in grpCols:
        for i in grpCols:
            if c!=i:
                grpBy=[c,i]
                grpBy=[c,i]
                df_tmp=df_orig.groupby(grpBy).agg({'id':'count','Exited':{'mean'}}).reset_index()
                df_tmp.columns=list(map(''.join, (list(df_tmp.columns.values))))
                sepCols=df_tmp.columns.drop(grpBy)+nm+'_ind_'+c+'-'+i
                df_tmp.columns=list(grpBy)+list(sepCols)
                #
                df_train=df_train.merge(df_tmp,how='left')
                df_test=df_test.merge(df_tmp,how='left')
                
                df_train[sepCols]=df_train[sepCols].fillna(0)
                df_test[sepCols]=df_test[sepCols].fillna(0)

                df_train[sepCols]=df_train[sepCols].astype('int')
                df_test[sepCols]=df_test[sepCols].astype('int')
    return df_train,df_test

In [13]:
def getGrps(df_orig,df_train,df_test,grpCols,nm):
    grpBy=[]
    for c in grpCols:
        grpBy.append(c)
        df_tmp=df_orig.groupby(grpBy).agg({'id':'count','Exited':{'sum'}}).reset_index()
        df_tmp.columns=list(map(''.join, (list(df_tmp.columns.values))))
        sepCols=df_tmp.columns.drop(grpBy)+nm+'_grps_'+c
        df_tmp.columns=list(grpBy)+list(sepCols)
                #
        df_train=df_train.merge(df_tmp,how='left')
        df_test=df_test.merge(df_tmp,how='left')
        
        df_train[sepCols]=df_train[sepCols].fillna(0)
        df_test[sepCols]=df_test[sepCols].fillna(0)
        
        df_train[sepCols]=df_train[sepCols].astype('int')
        df_test[sepCols]=df_test[sepCols].astype('int')
    return df_train,df_test

In [14]:
grpCols=['CustomerId', 'Surname', 'Geography', 'Gender', 'Age', 'Tenure', 'CreditScore', 
         'NumOfProducts','HasCrCard', 
         'IsActiveMember' ,'EstimatedSalary','Balance']
df_train,df_test=getGrps(df_orig,df_train,df_test,grpCols,'Orig_groups')
df_train,df_test=getGrpsIndv(df_orig,df_train,df_test,grpCols,'Orig_ind')

In [15]:
df_train.shape

(165034, 306)

In [16]:
df_train.head()

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,...,ididOrig_ind_ind_Balance-CreditScore,ExitedmeanOrig_ind_ind_Balance-CreditScore,ididOrig_ind_ind_Balance-NumOfProducts,ExitedmeanOrig_ind_ind_Balance-NumOfProducts,ididOrig_ind_ind_Balance-HasCrCard,ExitedmeanOrig_ind_ind_Balance-HasCrCard,ididOrig_ind_ind_Balance-IsActiveMember,ExitedmeanOrig_ind_ind_Balance-IsActiveMember,ididOrig_ind_ind_Balance-EstimatedSalary,ExitedmeanOrig_ind_ind_Balance-EstimatedSalary
0,0,15674932,Okwudilichukwu,668,France,Male,33.0,3,0.00,2,...,10,0,2600,0,2592,0,1744,0,0,0
1,1,15749177,Okwudiliolisa,627,France,Male,33.0,1,0.00,2,...,15,0,2600,0,2592,0,1873,0,0,0
2,2,15694510,Hsueh,678,France,Male,40.0,10,0.00,2,...,26,0,2600,0,2592,0,1744,0,0,0
3,3,15741417,Kao,581,France,Male,34.0,2,148882.54,1,...,0,0,0,0,0,0,0,0,0,0
4,4,15766172,Chiemenam,716,Spain,Male,33.0,5,0.00,2,...,11,0,2600,0,2592,0,1873,0,0,0

## Feature Engineering
- 기존 변수들을 활용한 신구 파생변수 생성
    - 장년층 여부, 나이 카테고리화, 신용카드와 활성사용자 여부 등

In [17]:
def getFeats(df):
    
    df['IsSenior'] = df['Age'].apply(lambda x: 1 if x >= 60 else 0)
    df['IsActive_by_CreditCard'] = df['HasCrCard'] * df['IsActiveMember']
    df['Products_Per_Tenure'] =  df['Tenure'] / df['NumOfProducts']
    df['AgeCat'] = np.round(df.Age/20).astype('int').astype('category')
    df['Sur_Geo_Gend_Sal'] = df['Surname']+df['Geography']+df['Gender']+np.round(df.EstimatedSalary).astype('str')
    
    df = df.merge(df_grps,how='left',on=['CustomerId', 'Surname', 'Geography', 'Gender'])
    df = df.merge(df_grps1,how='left',on=['CustomerId', 'Surname', 'Age', 'Gender'])
    df = df.merge(df_all_Exits,how='left')
    return df

In [18]:
df_train = getFeats(df_train)
df_test = getFeats(df_test)
##
feat_cols=df_train.columns.drop(['id','Exited'])
feat_cols=feat_cols.drop(scale_cols) #아예 기존 연속형 데이터는 전부 제거 -> 이미 전처리를 통해 모두 스케일링 / 범주화 / 통계화 시킴.
print("Number of Features:",len(feat_cols))
print(feat_cols)
df_train.head()

Number of Features: 352
Index(['CustomerId', 'Surname', 'Geography', 'Gender', 'Tenure',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'Age_scaled',
       'CreditScore_scaled',
       ...
       'EstimatedSalarygrps1sum', 'idgrps1count', 'Exit_lag1', 'Exit_lag2',
       'Exit_lag3', 'Exit_lead1', 'Exit_lead2', 'Exit_lead3',
       'Balance_lag_diff1', 'Balance_lead_diff1'],
      dtype='object', length=352)

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,...,EstimatedSalarygrps1sum,idgrps1count,Exit_lag1,Exit_lag2,Exit_lag3,Exit_lead1,Exit_lead2,Exit_lead3,Balance_lag_diff1,Balance_lead_diff1
0,0,15674932,Okwudilichukwu,668,France,Male,33.0,3,0.00,2,...,181449.97,1,-1,-1,-1,-1,-1,-1,0,0
1,1,15749177,Okwudiliolisa,627,France,Male,33.0,1,0.00,2,...,49503.50,1,-1,-1,-1,-1,-1,-1,115587,0
2,2,15694510,Hsueh,678,France,Male,40.0,10,0.00,2,...,184866.69,1,-1,-1,-1,-1,-1,-1,0,0
3,3,15741417,Kao,581,France,Male,34.0,2,148882.54,1,...,84560.88,1,-1,-1,-1,-1,-1,-1,0,0
4,4,15766172,Chiemenam,716,Spain,Male,33.0,5,0.00,2,...,15068.83,1,-1,-1,-1,-1,-1,-1,135759,142084

In [19]:
X=df_train[feat_cols]
y=df_train['Exited']
##
cat_features = np.where(X.dtypes != np.float64)[0]
cat_features

array([  0,   1,   2,   3,   4,   5,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
        32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
        97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
       123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
       136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
       149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
       162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
       175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187,
       188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200,
       201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
       214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226,
       227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
       240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
       253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265,
       266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278,
       279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291,
       292, 293, 294, 295, 296, 297, 298, 299, 300, 303, 304, 313, 318,
       319, 325, 331, 336, 337, 343, 344, 345, 346, 347, 348, 349, 350,
       351])

In [20]:
X.head(3)

,CustomerId,Surname,Geography,Gender,Tenure,NumOfProducts,HasCrCard,IsActiveMember,Age_scaled,CreditScore_scaled,...,EstimatedSalarygrps1sum,idgrps1count,Exit_lag1,Exit_lag2,Exit_lag3,Exit_lead1,Exit_lead2,Exit_lead3,Balance_lag_diff1,Balance_lead_diff1
0,15674932,Okwudilichukwu,France,Male,3,2,1.0,0.0,0.202703,0.636,...,181449.97,1,-1,-1,-1,-1,-1,-1,0,0
1,15749177,Okwudiliolisa,France,Male,1,2,1.0,1.0,0.202703,0.554,...,49503.50,1,-1,-1,-1,-1,-1,-1,115587,0
2,15694510,Hsueh,France,Male,10,2,1.0,0.0,0.297297,0.656,...,184866.69,1,-1,-1,-1,-1,-1,-1,0,0

# AutoGluon Test

In [22]:
df_train_AG = df_train.copy()
df_train_AG.pop('id')
df_train_AG.head(3)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,...,EstimatedSalarygrps1sum,idgrps1count,Exit_lag1,Exit_lag2,Exit_lag3,Exit_lead1,Exit_lead2,Exit_lead3,Balance_lag_diff1,Balance_lead_diff1
0,15674932,Okwudilichukwu,668,France,Male,33.0,3,0.0,2,1.0,...,181449.97,1,-1,-1,-1,-1,-1,-1,0,0
1,15749177,Okwudiliolisa,627,France,Male,33.0,1,0.0,2,1.0,...,49503.50,1,-1,-1,-1,-1,-1,-1,115587,0
2,15694510,Hsueh,678,France,Male,40.0,10,0.0,2,1.0,...,184866.69,1,-1,-1,-1,-1,-1,-1,0,0

In [23]:
df_test_AG = df_test.copy()
df_test_AG.pop('id')
df_test_AG.head(3)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,...,EstimatedSalarygrps1sum,idgrps1count,Exit_lag1,Exit_lag2,Exit_lag3,Exit_lead1,Exit_lead2,Exit_lead3,Balance_lag_diff1,Balance_lead_diff1
0,15773898,Lucchese,586,France,Female,23.0,2,0.0,2,0.0,...,160976.75,1,-1,-1,-1,-1,-1,-1,0,0
1,15782418,Nott,683,France,Female,46.0,2,0.0,1,1.0,...,72549.27,1,-1,-1,-1,-1,-1,-1,0,113909
2,15807120,K?,656,France,Female,34.0,7,0.0,2,1.0,...,138882.09,1,-1,-1,-1,-1,-1,-1,108891,0

In [24]:
automl = TabularPredictor(
    label='Exited',
    problem_type='binary',
    eval_metric='roc_auc')

No path specified. Models will be saved in: "AutogluonModels/ag-20241209_003221"

In [25]:
automl.fit(df_train_AG, presets='best_quality')
automl.leaderboard()

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.2
Python Version:     3.10.14
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Sun Nov 10 10:07:59 UTC 2024
CPU Count:          4
Memory Avail:       27.29 GB / 31.35 GB (87.1%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
Presets specified: ['best_quality']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2024-12-09 00:32:26,589	INFO worker.py:1744 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
		Context path: "/kaggle/working/AutogluonModels/ag-20241209_003221/ds_sub_fit/sub_fit_ho"
(_dystack pid=367) Running DyStack sub-fit ...
(_dystack pid=367) Beginning AutoGluon training ... Time limit = 893s
(_dystack pid=367) AutoGluon will save models to "/kaggle/working/AutogluonModels/ag-20241209_003221/ds_sub_fit/sub_fit_ho"
(_dystack pid=367) Train Data Rows:    146696
(_dystack pid=367) Train Data Columns: 356
(_dystack pid=367) Label Column:       Exited
(_dystack pid=367) Problem Type:       binary
(_dystack pid=367) Preprocessing data ...
(_dystack pid=367) Selected class <--> label mapping:  class 1 = 1, class 0 = 0
(_dystack pid=367) Using Feature Generators to preprocess the data ...
(_dystack pid=367) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=367) 	Available Memory:                    26598.38 MB
(_dystack pid=367) 	Train Data (Original)  Memory Usage: 430.80 MB (1.6% of available memory)
(_dystack pid=367) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=367) 	Stage 1 Generators:
(_dystack pid=367) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=367) 			Note: Converting 125 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=367) 	Stage 2 Generators:
(_dystack pid=367) 		Fitting FillNaFeatureGenerator...
(_dystack pid=367) 	Stage 3 Generators:
(_dystack pid=367) 		Fitting IdentityFeatureGenerator...
(_dystack pid=367) 		Fitting CategoryFeatureGenerator...
(_dystack pid=367) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=367) 	Stage 4 Generators:
(_dystack pid=367) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=367) 	Stage 5 Generators:
(_dystack pid=367) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=367) 	Useless Original Features (Count: 20): ['ExitedmeanOrig_ind_ind_Geography-Gender', 'ExitedmeanOrig_ind_ind_Geography-Tenure', 'ExitedmeanOrig_ind_ind_Geography-HasCrCard', 'ExitedmeanOrig_ind_ind_Geography-IsActiveMember', 'ExitedmeanOrig_ind_ind_Gender-Geography', 'ExitedmeanOrig_ind_ind_Gender-Tenure', 'ExitedmeanOrig_ind_ind_Gender-HasCrCard', 'ExitedmeanOrig_ind_ind_Gender-IsActiveMember', 'ExitedmeanOrig_ind_ind_Tenure-Geography', 'ExitedmeanOrig_ind_ind_Tenure-Gender', 'ExitedmeanOrig_ind_ind_Tenure-HasCrCard', 'ExitedmeanOrig_ind_ind_Tenure-IsActiveMember', 'ExitedmeanOrig_ind_ind_HasCrCard-Geography', 'ExitedmeanOrig_ind_ind_HasCrCard-Gender', 'ExitedmeanOrig_ind_ind_HasCrCard-Tenure', 'ExitedmeanOrig_ind_ind_HasCrCard-IsActiveMember', 'ExitedmeanOrig_ind_ind_IsActiveMember-Geography', 'ExitedmeanOrig_ind_ind_IsActiveMember-Gender', 'ExitedmeanOrig_ind_ind_IsActiveMember-Tenure', 'ExitedmeanOrig_ind_ind_IsActiveMember-HasCrCard']
(_dystack pid=367) 		These features carry no predictive signal and should be manually investigated.
(_dystack pid=367) 		This is typically a feature which has the same value for all rows.
(_dystack pid=367) 		These features do not need to be present at inference time.
(_dystack pid=367) 	Unused Original Features (Count: 131): ['ExitedsumOrig_groups_grps_IsActiveMember', 'ExitedsumOrig_groups_grps_EstimatedSalary', 'ExitedsumOrig_groups_grps_Balance', 'ididOrig_ind_ind_CustomerId-Surname', 'ididOrig_ind_ind_Surname-CustomerId', 'ExitedmeanOrig_ind_ind_Surname-CustomerId', 'ididOrig_ind_ind_Geography-CustomerId', 'ExitedmeanOrig_ind_ind_Geography-CustomerId', 'ididOrig_ind_ind_Geography-Surname', 'ExitedmeanOrig_ind_ind_Geography-Surname', 'ididOrig_ind_ind_Gender-CustomerId', 'ExitedmeanOrig_ind_ind_Gender-CustomerId', 'ididOrig_ind_ind_Gender-Surname', 'ExitedmeanOrig_ind_ind_Gender-Surname', 'ididOrig_ind_ind_Gender-Geography', 'ExitedmeanOrig_ind_ind_Gender-Age', 'ExitedmeanOrig_ind_ind_Gender-NumOfProducts', 'ididOrig_ind_ind_Age-CustomerId', 'ExitedmeanOrig_ind_ind_Age-CustomerId', 'ididOrig_ind_ind_Age-Surname', 'ExitedmeanOrig_ind_ind_Age-Surname', 'ididOrig_ind_ind_Age-Geography', 'ExitedmeanOrig_ind_ind_Age-Geography', 'ididOrig_ind_ind_Age-Gender', 'ExitedmeanOrig_ind_ind_Age-Gender', 'ExitedmeanOrig_ind_ind_Age-HasCrCard', 'ididOrig_ind_ind_Tenure-CustomerId', 'ExitedmeanOrig_ind_ind_Tenure-CustomerId', 'ididOrig_ind_ind_Tenure-Surname', 'ExitedmeanOrig_ind_ind_Tenure-Surname', 'ididOrig_ind_ind_Tenure-Geography', 'ididOrig_ind_ind_Tenure-Gender', 'ididOrig_ind_ind_Tenure-Age', 'ExitedmeanOrig_ind_ind_Tenure-Age', 'ididOrig_ind_ind_CreditScore-CustomerId', 'ExitedmeanOrig_ind_ind_CreditScore-CustomerId', 'ididOrig_ind_ind_CreditScore-Surname', 'ExitedmeanOrig_ind_ind_CreditScore-Surname', 'ididOrig_ind_ind_CreditScore-Geography', 'ExitedmeanOrig_ind_ind_CreditScore-Geography', 'ididOrig_ind_ind_CreditScore-Gender', 'ExitedmeanOrig_ind_ind_CreditScore-Gender', 'ididOrig_ind_ind_CreditScore-Age', 'ExitedmeanOrig_ind_ind_CreditScore-Age', 'ididOrig_ind_ind_CreditScore-Tenure', 'ExitedmeanOrig_ind_ind_CreditScore-Tenure', 'ididOrig_ind_ind_NumOfProducts-CustomerId', 'ExitedmeanOrig_ind_ind_NumOfProducts-CustomerId', 'ididOrig_ind_ind_NumOfProducts-Surname', 'ExitedmeanOrig_ind_ind_NumOfProducts-Surname', 'ididOrig_ind_ind_NumOfProducts-Geography', 'ExitedmeanOrig_ind_ind_NumOfProducts-Geography', 'ididOrig_ind_ind_NumOfProducts-Gender', 'ExitedmeanOrig_ind_ind_NumOfProducts-Gender', 'ididOrig_ind_ind_NumOfProducts-Age', 'ExitedmeanOrig_ind_ind_NumOfProducts-Age', 'ididOrig_ind_ind_NumOfProducts-Tenure', 'ExitedmeanOrig_ind_ind_NumOfProducts-Tenure', 'ididOrig_ind_ind_NumOfProducts-CreditScore', 'ExitedmeanOrig_ind_ind_NumOfProducts-CreditScore', 'ExitedmeanOrig_ind_ind_NumOfProducts-HasCrCard', 'ExitedmeanOrig_ind_ind_NumOfProducts-IsActiveMember', 'ididOrig_ind_ind_HasCrCard-CustomerId', 'ExitedmeanOrig_ind_ind_HasCrCard-CustomerId', 'ididOrig_ind_ind_HasCrCard-Surname', 'ExitedmeanOrig_ind_ind_HasCrCard-Surname', 'ididOrig_ind_ind_HasCrCard-Geography', 'ididOrig_ind_ind_HasCrCard-Gender', 'ididOrig_ind_ind_HasCrCard-Age', 'ExitedmeanOrig_ind_ind_HasCrCard-Age', 'ididOrig_ind_ind_HasCrCard-Tenure', 'ididOrig_ind_ind_HasCrCard-CreditScore', 'ExitedmeanOrig_ind_ind_HasCrCard-CreditScore', 'ididOrig_ind_ind_HasCrCard-NumOfProducts', 'ExitedmeanOrig_ind_ind_HasCrCard-NumOfProducts', 'ididOrig_ind_ind_IsActiveMember-CustomerId', 'ExitedmeanOrig_ind_ind_IsActiveMember-CustomerId', 'ididOrig_ind_ind_IsActiveMember-Surname', 'ExitedmeanOrig_ind_ind_IsActiveMember-Surname', 'ididOrig_ind_ind_IsActiveMember-Geography', 'ididOrig_ind_ind_IsActiveMember-Gender', 'ididOrig_ind_ind_IsActiveMember-Age', 'ExitedmeanOrig_ind_ind_IsActiveMember-Age', 'ididOrig_ind_ind_IsActiveMember-Tenure', 'ididOrig_ind_ind_IsActiveMember-CreditScore', 'ExitedmeanOrig_ind_ind_IsActiveMember-CreditScore', 'ididOrig_ind_ind_IsActiveMember-NumOfProducts', 'ExitedmeanOrig_ind_ind_IsActiveMember-NumOfProducts', 'ididOrig_ind_ind_IsActiveMember-HasCrCard', 'ididOrig_ind_ind_EstimatedSalary-CustomerId', 'ExitedmeanOrig_ind_ind_EstimatedSalary-CustomerId', 'ididOrig_ind_ind_EstimatedSalary-Surname', 'ExitedmeanOrig_ind_ind_EstimatedSalary-Surname', 'ididOrig_ind_ind_EstimatedSalary-Geography', 'ExitedmeanOrig_ind_ind_EstimatedSalary-Geography', 'ididOrig_ind_ind_EstimatedSalary-Gender', 'ExitedmeanOrig_ind_ind_EstimatedSalary-Gender', 'ididOrig_ind_ind_EstimatedSalary-Age', 'ExitedmeanOrig_ind_ind_EstimatedSalary-Age', 'ididOrig_ind_ind_EstimatedSalary-Tenure', 'ExitedmeanOrig_ind_ind_EstimatedSalary-Tenure', 'ididOrig_ind_ind_EstimatedSalary-CreditScore', 'ExitedmeanOrig_ind_ind_EstimatedSalary-CreditScore', 'ididOrig_ind_ind_EstimatedSalary-NumOfProducts', 'ExitedmeanOrig_ind_ind_EstimatedSalary-NumOfProducts', 'ididOrig_ind_ind_EstimatedSalary-HasCrCard', 'ExitedmeanOrig_ind_ind_EstimatedSalary-HasCrCard', 'ididOrig_ind_ind_EstimatedSalary-IsActiveMember', 'ExitedmeanOrig_ind_ind_EstimatedSalary-IsActiveMember', 'ididOrig_ind_ind_Balance-CustomerId', 'ExitedmeanOrig_ind_ind_Balance-CustomerId', 'ididOrig_ind_ind_Balance-Surname', 'ExitedmeanOrig_ind_ind_Balance-Surname', 'ididOrig_ind_ind_Balance-Geography', 'ExitedmeanOrig_ind_ind_Balance-Geography', 'ididOrig_ind_ind_Balance-Gender', 'ExitedmeanOrig_ind_ind_Balance-Gender', 'ididOrig_ind_ind_Balance-Age', 'ExitedmeanOrig_ind_ind_Balance-Age', 'ididOrig_ind_ind_Balance-Tenure', 'ExitedmeanOrig_ind_ind_Balance-Tenure', 'ididOrig_ind_ind_Balance-CreditScore', 'ExitedmeanOrig_ind_ind_Balance-CreditScore', 'ididOrig_ind_ind_Balance-NumOfProducts', 'ExitedmeanOrig_ind_ind_Balance-NumOfProducts', 'ididOrig_ind_ind_Balance-HasCrCard', 'ExitedmeanOrig_ind_ind_Balance-HasCrCard', 'ididOrig_ind_ind_Balance-IsActiveMember', 'ExitedmeanOrig_ind_ind_Balance-IsActiveMember', 'ididOrig_ind_ind_Balance-EstimatedSalary', 'ExitedmeanOrig_ind_ind_Balance-EstimatedSalary']
(_dystack pid=367) 		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
(_dystack pid=367) 		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
(_dystack pid=367) 		These features do not need to be present at inference time.
(_dystack pid=367) 		('int', []) : 131 | ['ExitedsumOrig_groups_grps_IsActiveMember', 'ExitedsumOrig_groups_grps_EstimatedSalary', 'ExitedsumOrig_groups_grps_Balance', 'ididOrig_ind_ind_CustomerId-Surname', 'ididOrig_ind_ind_Surname-CustomerId', ...]
(_dystack pid=367) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=367) 		('category', []) :   1 | ['AgeCat']
(_dystack pid=367) 		('float', [])    :  42 | ['Age', 'Balance', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', ...]
(_dystack pid=367) 		('int', [])      : 158 | ['CustomerId', 'CreditScore', 'Tenure', 'NumOfProducts', 'ididOrig_groups_grps_CustomerId', ...]
(_dystack pid=367) 		('object', [])   :   4 | ['Surname', 'Geography', 'Gender', 'Sur_Geo_Gend_Sal']
(_dystack pid=367) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=367) 		('category', [])  :   4 | ['Surname', 'Geography', 'AgeCat', 'Sur_Geo_Gend_Sal']
(_dystack pid=367) 		('float', [])     :  35 | ['Age', 'Balance', 'EstimatedSalary', 'Age_scaled', 'CreditScore_scaled', ...]
(_dystack pid=367) 		('int', [])       : 105 | ['CustomerId', 'CreditScore', 'Tenure', 'NumOfProducts', 'ididOrig_groups_grps_CustomerId', ...]
(_dystack pid=367) 		('int', ['bool']) :  61 | ['Gender', 'HasCrCard', 'IsActiveMember', 'ididOrig_groups_grps_Balance', 'ExitedmeanOrig_ind_ind_CustomerId-Surname', ...]
(_dystack pid=367) 	37.2s = Fit runtime
(_dystack pid=367) 	205 features in original data used to generate 205 features in processed data.
(_dystack pid=367) 	Train Data (Processed) Memory Usage: 166.06 MB (0.6% of available memory)
(_dystack pid=367) Data preprocessing and feature engineering runtime = 38.33s ...
(_dystack pid=367) AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
(_dystack pid=367) 	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
(_dystack pid=367) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=367) Large model count detected (112 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
(_dystack pid=367) User-specified model hyperparameters to be fit:
(_dystack pid=367) {
(_dystack pid=367) 	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
(_dystack pid=367) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=367) 	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
(_dystack pid=367) 	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
(_dystack pid=367) 	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
(_dystack pid=367) 	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=367) 	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=367) 	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
(_dystack pid=367) }
(_dystack pid=367) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=367) Fitting 110 L1 models, fit_strategy="sequential" ...
(_dystack pid=367) Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 569.68s of the 854.72s of remaining time.
(_dystack pid=367) 	0.5396	 = Validation score   (roc_auc)
(_dystack pid=367) 	2.13s	 = Training   runtime
(_dystack pid=367) 	59.4s	 = Validation runtime
(_dystack pid=367) Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 503.63s of the 788.67s of remaining time.
(_dystack pid=367) 	0.5362	 = Validation score   (roc_auc)
(_dystack pid=367) 	1.24s	 = Training   runtime
(_dystack pid=367) 	59.38s	 = Validation runtime
(_dystack pid=367) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 441.72s of the 726.76s of remaining time.
(_dystack pid=367) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=4.28%)
(_ray_fit pid=728) 	Ran out of time, early stopping on iteration 801. Best iteration is:
(_ray_fit pid=728) 	[681]	valid_set's binary_logloss: 0.301058
(_ray_fit pid=849) 	Ran out of time, early stopping on iteration 730. Best iteration is:
(_ray_fit pid=849) 	[549]	valid_set's binary_logloss: 0.298879
(_dystack pid=367) 	0.9042	 = Validation score   (roc_auc)
(_dystack pid=367) 	329.28s	 = Training   runtime
(_dystack pid=367) 	25.66s	 = Validation runtime
(_dystack pid=367) Fitting model: LightGBM_BAG_L1 ... Training model for up to 107.36s of the 392.40s of remaining time.
(_dystack pid=367) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=4.32%)
(_ray_fit pid=1006) 	Ran out of time, early stopping on iteration 77. Best iteration is:
(_ray_fit pid=1006) 	[77]	valid_set's binary_logloss: 0.309983
(_ray_fit pid=1127) 	Ran out of time, early stopping on iteration 74. Best iteration is: [repeated 4x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(_ray_fit pid=1127) 	[74]	valid_set's binary_logloss: 0.306012 [repeated 4x across cluster]
(_dystack pid=367) 	0.8978	 = Validation score   (roc_auc)
(_dystack pid=367) 	94.98s	 = Training   runtime
(_dystack pid=367) 	5.8s	 = Validation runtime
(_dystack pid=367) Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 6.60s of the 291.64s of remaining time.
(_dystack pid=367) 	Not enough time to generate out-of-fold predictions for model. Estimated time required was 40.57s compared to 10s of available time.
(_dystack pid=367) 	Time limit exceeded... Skipping RandomForestGini_BAG_L1.
(_ray_fit pid=1129) 	Ran out of time, early stopping on iteration 73. Best iteration is: [repeated 3x across cluster]
(_ray_fit pid=1129) 	[73]	valid_set's binary_logloss: 0.31107 [repeated 3x across cluster]
(_dystack pid=367) Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 168.33s of remaining time.
(_dystack pid=367) 	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.958, 'LightGBM_BAG_L1': 0.042}
(_dystack pid=367) 	0.9042	 = Validation score   (roc_auc)
(_dystack pid=367) 	2.88s	 = Training   runtime
(_dystack pid=367) 	0.03s	 = Validation runtime
(_dystack pid=367) Fitting 108 L2 models, fit_strategy="sequential" ...
(_dystack pid=367) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 165.40s of the 165.30s of remaining time.
(_dystack pid=367) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=4.52%)
(_ray_fit pid=1310) 	Ran out of time, early stopping on iteration 199. Best iteration is:
(_ray_fit pid=1310) 	[158]	valid_set's binary_logloss: 0.29639
(_dystack pid=367) 	0.9034	 = Validation score   (roc_auc)
(_dystack pid=367) 	135.1s	 = Training   runtime
(_dystack pid=367) 	5.75s	 = Validation runtime

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L3,0.905274,roc_auc,306.413256,2099.017906,0.033244,8.326104,3,True,12
1,WeightedEnsemble_L2,0.905087,roc_auc,111.675670,1399.656785,0.034079,5.825399,2,True,8
2,LightGBMXT_BAG_L1,0.904981,roc_auc,33.098098,435.560980,33.098098,435.560980,1,True,3
3,LightGBMXT_BAG_L2,0.904123,roc_auc,272.186836,1648.794144,7.436293,169.367414,2,True,9
4,LightGBM_BAG_L2,0.901230,roc_auc,271.011575,1614.111732,6.261033,134.685002,2,True,10
5,RandomForestGini_BAG_L2,0.899285,roc_auc,298.943719,1921.324389,34.193177,441.897658,2,True,11
6,LightGBM_BAG_L1,0.899211,roc_auc,12.851158,197.920998,12.851158,197.920998,1,True,4
7,CatBoost_BAG_L1,0.896357,roc_auc,1.210020,82.643744,1.210020,82.643744,1,True,7
8,RandomForestEntr_BAG_L1,0.891152,roc_auc,34.316213,388.997816,34.316213,388.997816,1,True,6
9,RandomForestGini_BAG_L1,0.890013,roc_auc,31.376121,371.351594,31.376121,371.351594,1,True,5
10,KNeighborsUnif_BAG_L1,0.539843,roc_auc,75.641077,1.685470,75.641077,1.685470,1,True,1
11,KNeighborsDist_BAG_L1,0.534944,roc_auc,76.257854,1.266130,76.257854,1.266130,1,True,2

In [ ]:
predictions = automl.predict_proba(df_test)
predictions0 = predictions[1]# AutoGluon의 Best Model로 예측
best_model_name = automl.leaderboard().iloc[0]['model']
print(f"AutoGluon Best Model: {best_model_name}")

# CatBoost

In [ ]:
RAND_VAL=27
num_folds = 9
n_est = 10000

In [ ]:
folds = StratifiedKFold(n_splits=num_folds,random_state=RAND_VAL,shuffle=True)
test_preds = np.empty((num_folds, len(df_test)))
auc_vals=[]

for n_fold, (train_idx, valid_idx) in enumerate(folds.split(X, y)):
    
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[valid_idx], y.iloc[valid_idx]
    
    train_pool = Pool(X_train, y_train,cat_features=cat_features)
    val_pool = Pool(X_val, y_val,cat_features=cat_features)
    
    clf = CatBoostClassifier(
    eval_metric='AUC',
    task_type='GPU',
    learning_rate=0.02,
    #depth = 7,
    iterations=n_est)
    clf.fit(train_pool, eval_set=val_pool,verbose=300)
    
    y_pred_val = clf.predict_proba(X_val[feat_cols])[:,1]
    auc_val = roc_auc_score(y_val, y_pred_val)
    print("AUC for fold ",n_fold,": ",auc_val)
    auc_vals.append(auc_val)
    
    y_pred_test = clf.predict_proba(df_test[feat_cols])[:,1]
    test_preds[n_fold, :] = y_pred_test
    print("----------------")

In [ ]:
join_cols=list(df_orig.columns.drop(['Exited']))
df_orig.rename(columns={'Exited':'Exited_Orig'},inplace=True)
df_orig['Exited_Orig']=df_orig['Exited_Orig'].map({0:1,1:0})
df_test_ov=df_test_ov.merge(df_orig,on=join_cols,how='left')[['id','Exited_Orig']].fillna(-1)
df_test_ov.head()

In [ ]:
catboost_predictions = test_preds.mean(axis=0)
df_sub = df_test_ov[['id','Exited_Orig']]
df_sub['Exited'] = np.where(df_sub.Exited_Orig==-1,catboost_predictions,df_sub.Exited_Orig)
df_sub.drop('Exited_Orig',axis=1,inplace=True)
df_sub.head()

# Enssemble Model
- Catboost + AutoGluon / 2

In [ ]:
# 앙상블: 단순 평균
ensemble_predictions = (predictions0 + catboost_predictions) / 2

In [ ]:
output_sample = pd.read_csv('/kaggle/input/playground-series-s4e1/sample_submission.csv')
output = pd.DataFrame({'id': output_sample.id, 'Exited': ensemble_predictions})
output.to_csv('submission.csv', index=False, sep=',')